name: Release a WDL workflow

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: Name of workflow to release
      release_type:
        description: major, minor, or patch
        default: patch
      release_notes:
        description: A text message summarizing the changes in this release

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  DEBIAN_FRONTEND: noninteractive
  GH_CLI_VERSION: 0.11.1
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

jobs:
  create_release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install release script dependencies
        run: |
          source /etc/profile
          sudo apt-get -qq update
          sudo apt-get -qq install -o=Dpkg::Use-Pty=0 --yes jq moreutils gettext httpie git curl
          curl -OLs https://github.com/cli/cli/releases/download/v${GH_CLI_VERSION}/gh_${GH_CLI_VERSION}_linux_amd64.deb
          sudo dpkg -i gh_${GH_CLI_VERSION}_linux_amd64.deb
      - name: Run release
        run: scripts/release.sh ${{github.event.inputs.workflow_name}} ${{github.event.inputs.release_type}} "${{github.event.inputs.release_notes}}"
      - name: Publish released workflow
        env:
          DEPLOYMENT_ENV: wdl
          DEPLOY_REF: main
          GITHUB_TOKEN: ${{secrets.GH_DEPLOY_TOKEN}}
          WORKFLOW_NAME: ${{github.event.inputs.workflow_name}}
        run: |
          deployment_args=$(jq -n ".auto_merge=false | .ref=env.DEPLOY_REF | .environment=env.DEPLOYMENT_ENV | .required_contexts=[] | .payload={workflow_name: env.WORKFLOW_NAME}")
          gh api repos/:owner/idseq/deployments --input - <<< "$deployment_args"
