name: WDL Unit Tests

on:
  push

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  DEBIAN_FRONTEND: noninteractive

jobs:
  linters:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Run linters
        run: |
          source /etc/profile
          sudo apt-get -qq update
          sudo apt-get -qq install --yes jq moreutils gettext make virtualenv zip unzip httpie git shellcheck ruby
          virtualenv --python=python3.6 .venv
          source .venv/bin/activate
          pip install -r requirements-dev.txt
          make lint
